# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-prisma-starter-new

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-store:
